language: node_js

node_js:
- "10"

cache:
  directories:
    - node_modules

# 배포 설정
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master

before_install:
  - npm install -g gatsby-cli

install:
  - npm install

before_script:
  - git config --global user.name 'Juhyung990122'
  - git config --global user.email 'harukawa99@naver.com'

script:
  - gatsby build && gh-pages -d public -r https://$GITHUB_TOKEN@github.com/Juhyung990122/Juhyung990122.github.io